// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite

import (
	"database/sql"
)

type Task struct {
	ID          int64
	Title       string
	Description sql.NullString
	DueDate     sql.NullTime
	AssignedTo  sql.NullInt64
	ParentID    sql.NullInt64
	Created     int64
	CreatedBy   int64
	Completed   sql.NullInt64
	CompletedBy sql.NullInt64
	Modified    int64
	ModifiedBy  sql.NullInt64
}

type User struct {
	ID        int64
	Name      string
	Email     string
	Created   int64
	CreatedBy int64
}
